### ISSUE TITLE
aws-lambda-adapter can't support url rewrite

### ISSUE THREAD

**Issue by liusushimeng** [aws-samples/aws-lambda-adapter#10]
In our scenario, AWS API Gateway resource url is /opa/v1/data,  but opa server running in lambda container only provide /v1/data api. So return 404 when aws-lambda-adapter forward request /opa/v1/data to opa server. If possbile to support url rewrite from /opa/v1/data to /v1/data by aws-lambda-adapter and send url /v1/data to opa server? Many Thanks.

**Comment by bnusunny** [comment]
Thanks for raising this requirement. This is a nice to have feature for the adapter in longer term. For short term workaround, either update application routing logic or package nginx inside the container to handle URL rewrite. You can checkout the [nginx example](https://github.com/aws-samples/aws-lambda-adapter/tree/main/examples/nginx) to understand the configuration.

**Comment by bnusunny** [comment]
@liusushimeng Just added this feature to Adapter. You can checkout the [SpringBoot](https://github.com/aws-samples/aws-lambda-adapter/tree/main/examples/springboot) example on main branch.
