### ISSUE TITLE
If possible to support wss protocol's web socket

### ISSUE THREAD

**Issue by liusushimeng** [aws-samples/aws-lambda-adapter#11]
Dear,

We want to use wss protocol's web socket to send message to browser from server side. If possible to support this feature? Looking forward to it.

Thanks
Wei Wang from Daimler China Cloud Team

**Comment by bnusunny** [comment]
Lambda Adapter does not support API Gateway Websocket endpoint. It require a complex setup to support Websocket, including setup a DynamoDB table to track websocket ConnectionIDs. We do not intent to support this in Lambda Adapter.
