### ISSUE TITLE
Need aws-lambda-adapter support a new way for deployment - via ZIP not only container

### ISSUE THREAD

**Issue by Crescent617** [aws-samples/aws-lambda-adapter#12]
Hello @bnusunny,

As we already have `CD pipeline` from `S3` to `lambda`, is there any way to deploy existing services using `aws-lambda-adapter` via `S3` (a zip package)?

**Comment by bnusunny** [comment]
This is possible using Custom Runtime. For other managed runtimes, I need to do some research.

**Comment by bnusunny** [comment]
@Crescent617  I added an example to show to use Lambda Adapter with managed runtimes. Check it out [here](https://github.com/aws-samples/aws-lambda-adapter/tree/dev/examples/expressjs-zip).

**Comment by rohanshiva** [comment]
@bnusunny is there an example of this extension running on a custom runtime?

**Comment by bnusunny** [comment]
Not yet. What language you use with a custom runtime? @rohanshiva

**Comment by rohanshiva** [comment]
@bnusunny I am just exploring custom runtimes so I wanted to see if there was already an example of this extension running on a custom runtime to learn a bit more. I don't have a language in my mind, but I am thinking of just creating a generic custom runtime that can run both node and python apps.

**Comment by bnusunny** [comment]
Custom runtime is more suitable for running PHP, rust, and other languages not have managed runtimes. I can create a simple example for running a web app written in Rust.

**Comment by rohanshiva** [comment]
@bnusunny that would be great

**Comment by bnusunny** [comment]
@rohanshiva I pushed an axum example in [PR#56](https://github.com/awslabs/aws-lambda-web-adapter/pull/56).

**Comment by rohanshiva** [comment]
thank you so much! @bnusunny
