### ISSUE TITLE
How does the `lambda-adapter` binary get executed?

### ISSUE THREAD

**Issue by peabnuts123** [aws-samples/aws-lambda-adapter#18]
Hi, probably a bit of a random question, but I'm just learning about how Lambda and how this `lambda-adapter` works. I understand how one can define and use a wrapper script (i.e. `AWS_LAMBDA_EXEC_WRAPPER`) or a [custom runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) to inject and modify how a Lambda function executes. But after studying [one of the examples](https://github.com/aws-samples/aws-lambda-adapter/tree/main/examples/expressjs-zip) for a long time, I can't figure out how the `/opt/extensions/lambda-adapter` binary should get invoked.

As far as I can tell. The `nodejs14.x` runtime will invoke the wrapper script `/opt/bootstrap`, which will replace the last argument with `"${LAMBDA_TASK_ROOT}/${_HANDLER}"` i.e. probably something like `/var/task/app.js`. This immediately takes the `node.js` runtime into the application's code (i.e. a simple express server) which doesn't leave any room for the `lambda-adapter` binary to be invoked.

The only thing I can think of is that the name `/opt/extensions/lambda-adapter` is a special path that the code within the `nodejs14.x` runtime knows to run. Is that the case? Or is there more setup missing here?

**Comment by bnusunny** [comment]
Hi Jeff, 

Great question! lambda-adapter is a Lambda extension. Lambda starts all extensions automatically in function init phase. You can see how this works in Lambda document [here](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html).

**Comment by peabnuts123** [comment]
Ahhh that is the missing piece of the puzzle, thank you! Does this mean that function's runtime starts up (say) an express.js server, the lambda-adapter _extension_ acts as a reverse-proxy that makes a request to that API, and then can somehow modify the payload to be the response received from the express server? The documentation kind of suggested that the runtime was still in-charge of serving the response, but in this use-case, the extension must have some "say" over that, yeah?

**Comment by bnusunny** [comment]
Correct. The wrapper script starts an express.js server and replaces the runtime process. Lambda Adapter is the proxy between Lambda runtime API and the express.js server. Adapter translates lambda events (json payload) into http requests, send them to the express.js server. When the express.js server send http response, lambda adapter converts it into the json response format and send it back to lambda runtime API.

**Comment by peabnuts123** [comment]
Wonderful. Thanks for taking the time to respond to me, and love your work. I am very interested in using this!
