### ISSUE TITLE
Why MUSL?

### ISSUE THREAD

**Issue by brainstorm** [aws-samples/aws-lambda-adapter#7]
Lambda Rust with `provided.al2` can run on native linux binaries: https://github.com/umccr/s3-rust-noodles-bam/tree/s3-server

See: https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306

**Comment by bnusunny** [comment]
For now, Lambda Adapter is used in container images, not custom runtime. 

We use musl to build Lambda Adapter as a statically linked binary, so that it works in any linux base images that customers may choose. It should even work in a blank baseimage such as SCRATCH.
